version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:16
    container_name: pg-bitnami
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=find_a_friend
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
